//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SizmekApiNet.App.AuthenticationService {
    
}


[System.ServiceModel.ServiceContractAttribute(Namespace="SizmekApiNet.App.AuthenticationService", ConfigurationName="IAuthenticationService")]
public interface IAuthenticationService {
    
    [System.ServiceModel.OperationContractAttribute(Action="http://api.eyeblaster.com/IAuthenticationService/ClientLogin", ReplyAction="http://api.eyeblaster.com/IAuthenticationService/ClientLoginResponse")]
    string ClientLogin(string username, string password, string applicationKey);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://api.eyeblaster.com/IAuthenticationService/ClientLogout", ReplyAction="http://api.eyeblaster.com/IAuthenticationService/ClientLogoutResponse")]
    void ClientLogout(string userSecurityToken);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://api.eyeblaster.com/IAuthenticationService/ClientImpersonation", ReplyAction="http://api.eyeblaster.com/IAuthenticationService/ClientImpersonationResponse")]
    string ClientImpersonation(string userSecurityToken, string username, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://api.eyeblaster.com/IAuthenticationService/GetClientInfo", ReplyAction="http://api.eyeblaster.com/IAuthenticationService/GetClientInfoResponse")]
    api.eyeblaster.com.V1.DataContracts.ClientInfo GetClientInfo();
}

public interface IAuthenticationServiceChannel : IAuthenticationService, System.ServiceModel.IClientChannel {
}

public class AuthenticationServiceClient : System.ServiceModel.ClientBase<IAuthenticationService>, IAuthenticationService {
    
    public AuthenticationServiceClient() {
    }
    
    public AuthenticationServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public AuthenticationServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public AuthenticationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public AuthenticationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress endpoint) : 
            base(binding, endpoint) {
    }
    
    public string ClientLogin(string username, string password, string applicationKey) {
        return base.Channel.ClientLogin(username, password, applicationKey);
    }
    
    public void ClientLogout(string userSecurityToken) {
        base.Channel.ClientLogout(userSecurityToken);
    }
    
    public string ClientImpersonation(string userSecurityToken, string username, string password) {
        return base.Channel.ClientImpersonation(userSecurityToken, username, password);
    }
    
    public api.eyeblaster.com.V1.DataContracts.ClientInfo GetClientInfo() {
        return base.Channel.GetClientInfo();
    }
}
namespace api.eyeblaster.com {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientLogin", Namespace="http://api.eyeblaster.com/")]
    public partial class ClientLogin : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string applicationKeyField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string applicationKey {
            get {
                return this.applicationKeyField;
            }
            set {
                this.applicationKeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientLoginResponse", Namespace="http://api.eyeblaster.com/")]
    public partial class ClientLoginResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ClientLoginResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientLoginResult {
            get {
                return this.ClientLoginResultField;
            }
            set {
                this.ClientLoginResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientLogout", Namespace="http://api.eyeblaster.com/")]
    public partial class ClientLogout : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string userSecurityTokenField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userSecurityToken {
            get {
                return this.userSecurityTokenField;
            }
            set {
                this.userSecurityTokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientLogoutResponse", Namespace="http://api.eyeblaster.com/")]
    public partial class ClientLogoutResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientImpersonation", Namespace="http://api.eyeblaster.com/")]
    public partial class ClientImpersonation : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string userSecurityTokenField;
        
        private string usernameField;
        
        private string passwordField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userSecurityToken {
            get {
                return this.userSecurityTokenField;
            }
            set {
                this.userSecurityTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientImpersonationResponse", Namespace="http://api.eyeblaster.com/")]
    public partial class ClientImpersonationResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ClientImpersonationResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientImpersonationResult {
            get {
                return this.ClientImpersonationResultField;
            }
            set {
                this.ClientImpersonationResultField = value;
            }
        }
    }
}
namespace api.eyeblaster.com.message {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetClientInfoRequest", Namespace="http://api.eyeblaster.com/message")]
    public partial class GetClientInfoRequest : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetClientInfoResponse", Namespace="http://api.eyeblaster.com/message")]
    public partial class GetClientInfoResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private api.eyeblaster.com.V1.DataContracts.ClientInfo ClientInfoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public api.eyeblaster.com.V1.DataContracts.ClientInfo ClientInfo {
            get {
                return this.ClientInfoField;
            }
            set {
                this.ClientInfoField = value;
            }
        }
    }
}
namespace api.eyeblaster.com.V1.DataContracts {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientInfo", Namespace="http://api.eyeblaster.com/V1/DataContracts")]
    public partial class ClientInfo : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AccountIDField;
        
        private string EmailField;
        
        private int TimeZoneField;
        
        private int UserIDField;
        
        private string UserNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int AccountID {
            get {
                return this.AccountIDField;
            }
            set {
                this.AccountIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TimeZone {
            get {
                return this.TimeZoneField;
            }
            set {
                this.TimeZoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                this.UserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                this.UserNameField = value;
            }
        }
    }
}
