//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SizmekApiNet.App.AnalyticsDataService {
    
}


[System.ServiceModel.ServiceContractAttribute(Namespace="SizmekApiNet.App.AnalyticsDataService", ConfigurationName="IAnalyticsDataService")]
public interface IAnalyticsDataService {
    
    [System.ServiceModel.OperationContractAttribute(Action="http://api.eyeblaster.com/IAnalyticsDataService/InitiateReportJob", ReplyAction="http://api.eyeblaster.com/IAnalyticsDataService/InitiateReportJobResponse")]
    api.eyeblaster.com.V1.DataContracts.ReportBase InitiateReportJob(api.eyeblaster.com.V1.DataContracts.ReportBase AnalyticsReport);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://api.eyeblaster.com/IAnalyticsDataService/GetReportJobStatus", ReplyAction="http://api.eyeblaster.com/IAnalyticsDataService/GetReportJobStatusResponse")]
    api.eyeblaster.com.V2.DataContracts.JobStatus GetReportJobStatus(api.eyeblaster.com.V1.DataContracts.ReportBase AnalyticsReport);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://api.eyeblaster.com/IAnalyticsDataService/GetReportAsURL", ReplyAction="http://api.eyeblaster.com/IAnalyticsDataService/GetReportAsURLResponse")]
    string GetReportAsURL(api.eyeblaster.com.V1.DataContracts.ReportBase AnalyticsReport);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://api.eyeblaster.com/IAnalyticsDataService/DeleteReport", ReplyAction="http://api.eyeblaster.com/IAnalyticsDataService/DeleteReportResponse")]
    void DeleteReport(api.eyeblaster.com.V1.DataContracts.ReportBase AnalyticsReport);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://api.eyeblaster.com/IAnalyticsDataService/GetReportsLastAggregationTime", ReplyAction="http://api.eyeblaster.com/IAnalyticsDataService/GetReportsLastAggregationTimeResp" +
        "onse")]
    api.eyeblaster.com.V1.DataContracts.APIDateTime GetReportsLastAggregationTime();
}

public interface IAnalyticsDataServiceChannel : IAnalyticsDataService, System.ServiceModel.IClientChannel {
}

public class AnalyticsDataServiceClient : System.ServiceModel.ClientBase<IAnalyticsDataService>, IAnalyticsDataService {
    
    public AnalyticsDataServiceClient() {
    }
    
    public AnalyticsDataServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public AnalyticsDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public AnalyticsDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public AnalyticsDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress endpoint) : 
            base(binding, endpoint) {
    }
    
    public api.eyeblaster.com.V1.DataContracts.ReportBase InitiateReportJob(api.eyeblaster.com.V1.DataContracts.ReportBase AnalyticsReport) {
        return base.Channel.InitiateReportJob(AnalyticsReport);
    }
    
    public api.eyeblaster.com.V2.DataContracts.JobStatus GetReportJobStatus(api.eyeblaster.com.V1.DataContracts.ReportBase AnalyticsReport) {
        return base.Channel.GetReportJobStatus(AnalyticsReport);
    }
    
    public string GetReportAsURL(api.eyeblaster.com.V1.DataContracts.ReportBase AnalyticsReport) {
        return base.Channel.GetReportAsURL(AnalyticsReport);
    }
    
    public void DeleteReport(api.eyeblaster.com.V1.DataContracts.ReportBase AnalyticsReport) {
        base.Channel.DeleteReport(AnalyticsReport);
    }
    
    public api.eyeblaster.com.V1.DataContracts.APIDateTime GetReportsLastAggregationTime() {
        return base.Channel.GetReportsLastAggregationTime();
    }
}
namespace api.eyeblaster.com.message {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InitiateAnalyticsReportJobRequest", Namespace="http://api.eyeblaster.com/message")]
    public partial class InitiateAnalyticsReportJobRequest : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private api.eyeblaster.com.V1.DataContracts.ReportBase AnalyticsReportField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public api.eyeblaster.com.V1.DataContracts.ReportBase AnalyticsReport {
            get {
                return this.AnalyticsReportField;
            }
            set {
                this.AnalyticsReportField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InitiateAnalyticsReportJobResponse", Namespace="http://api.eyeblaster.com/message")]
    public partial class InitiateAnalyticsReportJobResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private api.eyeblaster.com.V1.DataContracts.ReportBase AnalyticsReportField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public api.eyeblaster.com.V1.DataContracts.ReportBase AnalyticsReport {
            get {
                return this.AnalyticsReportField;
            }
            set {
                this.AnalyticsReportField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAnalyticsReportJobStatusRequest", Namespace="http://api.eyeblaster.com/message")]
    public partial class GetAnalyticsReportJobStatusRequest : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private api.eyeblaster.com.V1.DataContracts.ReportBase AnalyticsReportField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public api.eyeblaster.com.V1.DataContracts.ReportBase AnalyticsReport {
            get {
                return this.AnalyticsReportField;
            }
            set {
                this.AnalyticsReportField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAnalyticsReportJobStatusResponse", Namespace="http://api.eyeblaster.com/message")]
    public partial class GetAnalyticsReportJobStatusResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private api.eyeblaster.com.V2.DataContracts.JobStatus StatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public api.eyeblaster.com.V2.DataContracts.JobStatus Status {
            get {
                return this.StatusField;
            }
            set {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAnalyticsReportAsURLRequest", Namespace="http://api.eyeblaster.com/message")]
    public partial class GetAnalyticsReportAsURLRequest : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private api.eyeblaster.com.V1.DataContracts.ReportBase AnalyticsReportField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public api.eyeblaster.com.V1.DataContracts.ReportBase AnalyticsReport {
            get {
                return this.AnalyticsReportField;
            }
            set {
                this.AnalyticsReportField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAnalyticsReportAsURLResponse", Namespace="http://api.eyeblaster.com/message")]
    public partial class GetAnalyticsReportAsURLResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string URLField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                this.URLField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteAnalyticsReportRequest", Namespace="http://api.eyeblaster.com/message")]
    public partial class DeleteAnalyticsReportRequest : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private api.eyeblaster.com.V1.DataContracts.ReportBase AnalyticsReportField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public api.eyeblaster.com.V1.DataContracts.ReportBase AnalyticsReport {
            get {
                return this.AnalyticsReportField;
            }
            set {
                this.AnalyticsReportField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetReportsLastAggregationTimeRequest", Namespace="http://api.eyeblaster.com/message")]
    public partial class GetReportsLastAggregationTimeRequest : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetReportsLastAggregationTimeResponse", Namespace="http://api.eyeblaster.com/message")]
    public partial class GetReportsLastAggregationTimeResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private api.eyeblaster.com.V1.DataContracts.APIDateTime DateTimeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public api.eyeblaster.com.V1.DataContracts.APIDateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                this.DateTimeField = value;
            }
        }
    }
}
namespace api.eyeblaster.com.V1.DataContracts {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportBase", Namespace="http://api.eyeblaster.com/V1/DataContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(api.eyeblaster.com.V1.DataContracts.DynamicPerformanceReport))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(api.eyeblaster.com.V1.DataContracts.PerformanceReport))]
    public partial class ReportBase : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long JobIDField;
        
        private string UniqueNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long JobID {
            get {
                return this.JobIDField;
            }
            set {
                this.JobIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UniqueName {
            get {
                return this.UniqueNameField;
            }
            set {
                this.UniqueNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DynamicPerformanceReport", Namespace="http://api.eyeblaster.com/V1/DataContracts")]
    public partial class DynamicPerformanceReport : api.eyeblaster.com.V1.DataContracts.ReportBase {
        
        private string AdIDField;
        
        private string CampaignIDField;
        
        private System.Nullable<int> ConversionAttributionModelField;
        
        private string ConversionTagsIDsFiltersField;
        
        private System.Nullable<int> CookieWindowClicksField;
        
        private System.Nullable<int> CookieWindowImpressionsField;
        
        private string CustomFilter1Field;
        
        private string CustomFilter2Field;
        
        private string CustomFilter3Field;
        
        private string CustomFilter4Field;
        
        private string CustomFilter5Field;
        
        private string CustomFilter6Field;
        
        private int CustomizationParameterField;
        
        private System.Nullable<int> DataLevelIDField;
        
        private System.Nullable<bool> IsIgnoreAssignmentToCampaignField;
        
        private string PackageIDField;
        
        private string PlacementIDField;
        
        private api.eyeblaster.com.V1.DataContracts.APIDateTime ReporEndtDateField;
        
        private api.eyeblaster.com.V1.DataContracts.APIDateTime ReportStartDateField;
        
        private string SiteIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AdID {
            get {
                return this.AdIDField;
            }
            set {
                this.AdIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CampaignID {
            get {
                return this.CampaignIDField;
            }
            set {
                this.CampaignIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> ConversionAttributionModel {
            get {
                return this.ConversionAttributionModelField;
            }
            set {
                this.ConversionAttributionModelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ConversionTagsIDsFilters {
            get {
                return this.ConversionTagsIDsFiltersField;
            }
            set {
                this.ConversionTagsIDsFiltersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> CookieWindowClicks {
            get {
                return this.CookieWindowClicksField;
            }
            set {
                this.CookieWindowClicksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> CookieWindowImpressions {
            get {
                return this.CookieWindowImpressionsField;
            }
            set {
                this.CookieWindowImpressionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CustomFilter1 {
            get {
                return this.CustomFilter1Field;
            }
            set {
                this.CustomFilter1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CustomFilter2 {
            get {
                return this.CustomFilter2Field;
            }
            set {
                this.CustomFilter2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CustomFilter3 {
            get {
                return this.CustomFilter3Field;
            }
            set {
                this.CustomFilter3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CustomFilter4 {
            get {
                return this.CustomFilter4Field;
            }
            set {
                this.CustomFilter4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CustomFilter5 {
            get {
                return this.CustomFilter5Field;
            }
            set {
                this.CustomFilter5Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CustomFilter6 {
            get {
                return this.CustomFilter6Field;
            }
            set {
                this.CustomFilter6Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CustomizationParameter {
            get {
                return this.CustomizationParameterField;
            }
            set {
                this.CustomizationParameterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> DataLevelID {
            get {
                return this.DataLevelIDField;
            }
            set {
                this.DataLevelIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<bool> IsIgnoreAssignmentToCampaign {
            get {
                return this.IsIgnoreAssignmentToCampaignField;
            }
            set {
                this.IsIgnoreAssignmentToCampaignField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PackageID {
            get {
                return this.PackageIDField;
            }
            set {
                this.PackageIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PlacementID {
            get {
                return this.PlacementIDField;
            }
            set {
                this.PlacementIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public api.eyeblaster.com.V1.DataContracts.APIDateTime ReporEndtDate {
            get {
                return this.ReporEndtDateField;
            }
            set {
                this.ReporEndtDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public api.eyeblaster.com.V1.DataContracts.APIDateTime ReportStartDate {
            get {
                return this.ReportStartDateField;
            }
            set {
                this.ReportStartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SiteID {
            get {
                return this.SiteIDField;
            }
            set {
                this.SiteIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PerformanceReport", Namespace="http://api.eyeblaster.com/V1/DataContracts")]
    public partial class PerformanceReport : api.eyeblaster.com.V1.DataContracts.ReportBase {
        
        private int CampaignIDField;
        
        private System.Nullable<int> ConversionAttributionModelField;
        
        private string ConversionTagsIDsFiltersField;
        
        private System.Nullable<int> CookieWindowClicksField;
        
        private System.Nullable<int> CookieWindowImpressionsField;
        
        private System.Nullable<int> DataLevelIDField;
        
        private System.Nullable<bool> IsIgnoreAssignmentToCampaignField;
        
        private api.eyeblaster.com.V1.DataContracts.APIDateTime ReporEndtDateField;
        
        private api.eyeblaster.com.V1.DataContracts.APIDateTime ReportStartDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CampaignID {
            get {
                return this.CampaignIDField;
            }
            set {
                this.CampaignIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> ConversionAttributionModel {
            get {
                return this.ConversionAttributionModelField;
            }
            set {
                this.ConversionAttributionModelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ConversionTagsIDsFilters {
            get {
                return this.ConversionTagsIDsFiltersField;
            }
            set {
                this.ConversionTagsIDsFiltersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> CookieWindowClicks {
            get {
                return this.CookieWindowClicksField;
            }
            set {
                this.CookieWindowClicksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> CookieWindowImpressions {
            get {
                return this.CookieWindowImpressionsField;
            }
            set {
                this.CookieWindowImpressionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> DataLevelID {
            get {
                return this.DataLevelIDField;
            }
            set {
                this.DataLevelIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<bool> IsIgnoreAssignmentToCampaign {
            get {
                return this.IsIgnoreAssignmentToCampaignField;
            }
            set {
                this.IsIgnoreAssignmentToCampaignField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public api.eyeblaster.com.V1.DataContracts.APIDateTime ReporEndtDate {
            get {
                return this.ReporEndtDateField;
            }
            set {
                this.ReporEndtDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public api.eyeblaster.com.V1.DataContracts.APIDateTime ReportStartDate {
            get {
                return this.ReportStartDateField;
            }
            set {
                this.ReportStartDateField = value;
            }
        }
    }
}

namespace api.eyeblaster.com.V2.DataContracts {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobStatus", Namespace="http://api.eyeblaster.com/V2/DataContracts")]
    public enum JobStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Completed = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute(Value="In Progress")]
        InProgress = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 2,
    }
}
