//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SizmekApiNet.App.AnalyticsDataService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportBase", Namespace="http://api.eyeblaster.com/V1/DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SizmekApiNet.App.AnalyticsDataService.DynamicPerformanceReport))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SizmekApiNet.App.AnalyticsDataService.PerformanceReport))]
    public partial class ReportBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long JobIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UniqueNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long JobID {
            get {
                return this.JobIDField;
            }
            set {
                if ((this.JobIDField.Equals(value) != true)) {
                    this.JobIDField = value;
                    this.RaisePropertyChanged("JobID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UniqueName {
            get {
                return this.UniqueNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UniqueNameField, value) != true)) {
                    this.UniqueNameField = value;
                    this.RaisePropertyChanged("UniqueName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DynamicPerformanceReport", Namespace="http://api.eyeblaster.com/V1/DataContracts")]
    [System.SerializableAttribute()]
    public partial class DynamicPerformanceReport : SizmekApiNet.App.AnalyticsDataService.ReportBase {
        
        private string AdIDField;
        
        private string CampaignIDField;
        
        private System.Nullable<int> ConversionAttributionModelField;
        
        private string ConversionTagsIDsFiltersField;
        
        private System.Nullable<int> CookieWindowClicksField;
        
        private System.Nullable<int> CookieWindowImpressionsField;
        
        private string CustomFilter1Field;
        
        private string CustomFilter2Field;
        
        private string CustomFilter3Field;
        
        private string CustomFilter4Field;
        
        private string CustomFilter5Field;
        
        private string CustomFilter6Field;
        
        private int CustomizationParameterField;
        
        private System.Nullable<int> DataLevelIDField;
        
        private System.Nullable<bool> IsIgnoreAssignmentToCampaignField;
        
        private string PackageIDField;
        
        private string PlacementIDField;
        
        private SizmekApiNet.App.AnalyticsDataService.APIDateTime ReporEndtDateField;
        
        private SizmekApiNet.App.AnalyticsDataService.APIDateTime ReportStartDateField;
        
        private string SiteIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AdID {
            get {
                return this.AdIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AdIDField, value) != true)) {
                    this.AdIDField = value;
                    this.RaisePropertyChanged("AdID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CampaignID {
            get {
                return this.CampaignIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CampaignIDField, value) != true)) {
                    this.CampaignIDField = value;
                    this.RaisePropertyChanged("CampaignID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> ConversionAttributionModel {
            get {
                return this.ConversionAttributionModelField;
            }
            set {
                if ((this.ConversionAttributionModelField.Equals(value) != true)) {
                    this.ConversionAttributionModelField = value;
                    this.RaisePropertyChanged("ConversionAttributionModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ConversionTagsIDsFilters {
            get {
                return this.ConversionTagsIDsFiltersField;
            }
            set {
                if ((object.ReferenceEquals(this.ConversionTagsIDsFiltersField, value) != true)) {
                    this.ConversionTagsIDsFiltersField = value;
                    this.RaisePropertyChanged("ConversionTagsIDsFilters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> CookieWindowClicks {
            get {
                return this.CookieWindowClicksField;
            }
            set {
                if ((this.CookieWindowClicksField.Equals(value) != true)) {
                    this.CookieWindowClicksField = value;
                    this.RaisePropertyChanged("CookieWindowClicks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> CookieWindowImpressions {
            get {
                return this.CookieWindowImpressionsField;
            }
            set {
                if ((this.CookieWindowImpressionsField.Equals(value) != true)) {
                    this.CookieWindowImpressionsField = value;
                    this.RaisePropertyChanged("CookieWindowImpressions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CustomFilter1 {
            get {
                return this.CustomFilter1Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomFilter1Field, value) != true)) {
                    this.CustomFilter1Field = value;
                    this.RaisePropertyChanged("CustomFilter1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CustomFilter2 {
            get {
                return this.CustomFilter2Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomFilter2Field, value) != true)) {
                    this.CustomFilter2Field = value;
                    this.RaisePropertyChanged("CustomFilter2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CustomFilter3 {
            get {
                return this.CustomFilter3Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomFilter3Field, value) != true)) {
                    this.CustomFilter3Field = value;
                    this.RaisePropertyChanged("CustomFilter3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CustomFilter4 {
            get {
                return this.CustomFilter4Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomFilter4Field, value) != true)) {
                    this.CustomFilter4Field = value;
                    this.RaisePropertyChanged("CustomFilter4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CustomFilter5 {
            get {
                return this.CustomFilter5Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomFilter5Field, value) != true)) {
                    this.CustomFilter5Field = value;
                    this.RaisePropertyChanged("CustomFilter5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CustomFilter6 {
            get {
                return this.CustomFilter6Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomFilter6Field, value) != true)) {
                    this.CustomFilter6Field = value;
                    this.RaisePropertyChanged("CustomFilter6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CustomizationParameter {
            get {
                return this.CustomizationParameterField;
            }
            set {
                if ((this.CustomizationParameterField.Equals(value) != true)) {
                    this.CustomizationParameterField = value;
                    this.RaisePropertyChanged("CustomizationParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> DataLevelID {
            get {
                return this.DataLevelIDField;
            }
            set {
                if ((this.DataLevelIDField.Equals(value) != true)) {
                    this.DataLevelIDField = value;
                    this.RaisePropertyChanged("DataLevelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<bool> IsIgnoreAssignmentToCampaign {
            get {
                return this.IsIgnoreAssignmentToCampaignField;
            }
            set {
                if ((this.IsIgnoreAssignmentToCampaignField.Equals(value) != true)) {
                    this.IsIgnoreAssignmentToCampaignField = value;
                    this.RaisePropertyChanged("IsIgnoreAssignmentToCampaign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PackageID {
            get {
                return this.PackageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PackageIDField, value) != true)) {
                    this.PackageIDField = value;
                    this.RaisePropertyChanged("PackageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PlacementID {
            get {
                return this.PlacementIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PlacementIDField, value) != true)) {
                    this.PlacementIDField = value;
                    this.RaisePropertyChanged("PlacementID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public SizmekApiNet.App.AnalyticsDataService.APIDateTime ReporEndtDate {
            get {
                return this.ReporEndtDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ReporEndtDateField, value) != true)) {
                    this.ReporEndtDateField = value;
                    this.RaisePropertyChanged("ReporEndtDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public SizmekApiNet.App.AnalyticsDataService.APIDateTime ReportStartDate {
            get {
                return this.ReportStartDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportStartDateField, value) != true)) {
                    this.ReportStartDateField = value;
                    this.RaisePropertyChanged("ReportStartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SiteID {
            get {
                return this.SiteIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteIDField, value) != true)) {
                    this.SiteIDField = value;
                    this.RaisePropertyChanged("SiteID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PerformanceReport", Namespace="http://api.eyeblaster.com/V1/DataContracts")]
    [System.SerializableAttribute()]
    public partial class PerformanceReport : SizmekApiNet.App.AnalyticsDataService.ReportBase {
        
        private int CampaignIDField;
        
        private System.Nullable<int> ConversionAttributionModelField;
        
        private string ConversionTagsIDsFiltersField;
        
        private System.Nullable<int> CookieWindowClicksField;
        
        private System.Nullable<int> CookieWindowImpressionsField;
        
        private System.Nullable<int> DataLevelIDField;
        
        private System.Nullable<bool> IsIgnoreAssignmentToCampaignField;
        
        private SizmekApiNet.App.AnalyticsDataService.APIDateTime ReporEndtDateField;
        
        private SizmekApiNet.App.AnalyticsDataService.APIDateTime ReportStartDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CampaignID {
            get {
                return this.CampaignIDField;
            }
            set {
                if ((this.CampaignIDField.Equals(value) != true)) {
                    this.CampaignIDField = value;
                    this.RaisePropertyChanged("CampaignID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> ConversionAttributionModel {
            get {
                return this.ConversionAttributionModelField;
            }
            set {
                if ((this.ConversionAttributionModelField.Equals(value) != true)) {
                    this.ConversionAttributionModelField = value;
                    this.RaisePropertyChanged("ConversionAttributionModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ConversionTagsIDsFilters {
            get {
                return this.ConversionTagsIDsFiltersField;
            }
            set {
                if ((object.ReferenceEquals(this.ConversionTagsIDsFiltersField, value) != true)) {
                    this.ConversionTagsIDsFiltersField = value;
                    this.RaisePropertyChanged("ConversionTagsIDsFilters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> CookieWindowClicks {
            get {
                return this.CookieWindowClicksField;
            }
            set {
                if ((this.CookieWindowClicksField.Equals(value) != true)) {
                    this.CookieWindowClicksField = value;
                    this.RaisePropertyChanged("CookieWindowClicks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> CookieWindowImpressions {
            get {
                return this.CookieWindowImpressionsField;
            }
            set {
                if ((this.CookieWindowImpressionsField.Equals(value) != true)) {
                    this.CookieWindowImpressionsField = value;
                    this.RaisePropertyChanged("CookieWindowImpressions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> DataLevelID {
            get {
                return this.DataLevelIDField;
            }
            set {
                if ((this.DataLevelIDField.Equals(value) != true)) {
                    this.DataLevelIDField = value;
                    this.RaisePropertyChanged("DataLevelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<bool> IsIgnoreAssignmentToCampaign {
            get {
                return this.IsIgnoreAssignmentToCampaignField;
            }
            set {
                if ((this.IsIgnoreAssignmentToCampaignField.Equals(value) != true)) {
                    this.IsIgnoreAssignmentToCampaignField = value;
                    this.RaisePropertyChanged("IsIgnoreAssignmentToCampaign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public SizmekApiNet.App.AnalyticsDataService.APIDateTime ReporEndtDate {
            get {
                return this.ReporEndtDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ReporEndtDateField, value) != true)) {
                    this.ReporEndtDateField = value;
                    this.RaisePropertyChanged("ReporEndtDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public SizmekApiNet.App.AnalyticsDataService.APIDateTime ReportStartDate {
            get {
                return this.ReportStartDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportStartDateField, value) != true)) {
                    this.ReportStartDateField = value;
                    this.RaisePropertyChanged("ReportStartDate");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIDateTime", Namespace="http://api.eyeblaster.com/V1/DataContracts")]
    [System.SerializableAttribute()]
    public partial class APIDateTime : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int YearField;
        
        private int MonthField;
        
        private int DayField;
        
        private int HourField;
        
        private int MinuteField;
        
        private int SecondField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<SizmekApiNet.App.AnalyticsDataService.TimeZone> TimeZoneIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Month {
            get {
                return this.MonthField;
            }
            set {
                if ((this.MonthField.Equals(value) != true)) {
                    this.MonthField = value;
                    this.RaisePropertyChanged("Month");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Day {
            get {
                return this.DayField;
            }
            set {
                if ((this.DayField.Equals(value) != true)) {
                    this.DayField = value;
                    this.RaisePropertyChanged("Day");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Hour {
            get {
                return this.HourField;
            }
            set {
                if ((this.HourField.Equals(value) != true)) {
                    this.HourField = value;
                    this.RaisePropertyChanged("Hour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Minute {
            get {
                return this.MinuteField;
            }
            set {
                if ((this.MinuteField.Equals(value) != true)) {
                    this.MinuteField = value;
                    this.RaisePropertyChanged("Minute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Second {
            get {
                return this.SecondField;
            }
            set {
                if ((this.SecondField.Equals(value) != true)) {
                    this.SecondField = value;
                    this.RaisePropertyChanged("Second");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<SizmekApiNet.App.AnalyticsDataService.TimeZone> TimeZoneID {
            get {
                return this.TimeZoneIDField;
            }
            set {
                if ((this.TimeZoneIDField.Equals(value) != true)) {
                    this.TimeZoneIDField = value;
                    this.RaisePropertyChanged("TimeZoneID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeZone", Namespace="http://api.eyeblaster.com/V1/DataContracts")]
    public enum TimeZone : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_Minus_12 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_Minus_11 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_Minus_10 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_Minus_9 = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_Minus_8 = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_Minus_7 = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_Minus_6 = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_Minus_5 = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_Minus_4 = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_Minus_3 = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_Minus_2 = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_Minus_1 = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_Plus_1 = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_Plus_2 = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_Plus_3 = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_Plus_4 = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_Plus_5 = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_Plus_6 = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_Plus_7 = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_Plus_8 = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_Plus_9 = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_Plus_10 = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_Plus_11 = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_Plus_12 = 25,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobStatus", Namespace="http://api.eyeblaster.com/V2/DataContracts")]
    public enum JobStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Completed = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute(Value="In Progress")]
        InProgress = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.eyeblaster.com/", ConfigurationName="AnalyticsDataService.IAnalyticsDataService")]
    public interface IAnalyticsDataService {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://api.eyeblaster.com/message) of message InitiateAnalyticsReportJobRequest does not match the default value (http://api.eyeblaster.com/)
        [System.ServiceModel.OperationContractAttribute(Action="http://api.eyeblaster.com/IAnalyticsDataService/InitiateReportJob", ReplyAction="http://api.eyeblaster.com/IAnalyticsDataService/InitiateReportJobResponse")]
        SizmekApiNet.App.AnalyticsDataService.InitiateAnalyticsReportJobResponse InitiateReportJob(SizmekApiNet.App.AnalyticsDataService.InitiateAnalyticsReportJobRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://api.eyeblaster.com/message) of message GetAnalyticsReportJobStatusRequest does not match the default value (http://api.eyeblaster.com/)
        [System.ServiceModel.OperationContractAttribute(Action="http://api.eyeblaster.com/IAnalyticsDataService/GetReportJobStatus", ReplyAction="http://api.eyeblaster.com/IAnalyticsDataService/GetReportJobStatusResponse")]
        SizmekApiNet.App.AnalyticsDataService.GetAnalyticsReportJobStatusResponse GetReportJobStatus(SizmekApiNet.App.AnalyticsDataService.GetAnalyticsReportJobStatusRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://api.eyeblaster.com/message) of message GetAnalyticsReportAsURLRequest does not match the default value (http://api.eyeblaster.com/)
        [System.ServiceModel.OperationContractAttribute(Action="http://api.eyeblaster.com/IAnalyticsDataService/GetReportAsURL", ReplyAction="http://api.eyeblaster.com/IAnalyticsDataService/GetReportAsURLResponse")]
        SizmekApiNet.App.AnalyticsDataService.GetAnalyticsReportAsURLResponse GetReportAsURL(SizmekApiNet.App.AnalyticsDataService.GetAnalyticsReportAsURLRequest request);
        
        // CODEGEN: Generating message contract since the operation DeleteReport is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://api.eyeblaster.com/IAnalyticsDataService/DeleteReport", ReplyAction="http://api.eyeblaster.com/IAnalyticsDataService/DeleteReportResponse")]
        SizmekApiNet.App.AnalyticsDataService.DeleteReportResponse DeleteReport(SizmekApiNet.App.AnalyticsDataService.DeleteAnalyticsReportRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://api.eyeblaster.com/message) of message GetReportsLastAggregationTimeRequest does not match the default value (http://api.eyeblaster.com/)
        [System.ServiceModel.OperationContractAttribute(Action="http://api.eyeblaster.com/IAnalyticsDataService/GetReportsLastAggregationTime", ReplyAction="http://api.eyeblaster.com/IAnalyticsDataService/GetReportsLastAggregationTimeResp" +
            "onse")]
        SizmekApiNet.App.AnalyticsDataService.GetReportsLastAggregationTimeResponse GetReportsLastAggregationTime(SizmekApiNet.App.AnalyticsDataService.GetReportsLastAggregationTimeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InitiateAnalyticsReportJobRequest", WrapperNamespace="http://api.eyeblaster.com/message", IsWrapped=true)]
    public partial class InitiateAnalyticsReportJobRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.eyeblaster.com/message")]
        public string UserSecurityToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.eyeblaster.com/message", Order=0)]
        public SizmekApiNet.App.AnalyticsDataService.ReportBase AnalyticsReport;
        
        public InitiateAnalyticsReportJobRequest() {
        }
        
        public InitiateAnalyticsReportJobRequest(string UserSecurityToken, SizmekApiNet.App.AnalyticsDataService.ReportBase AnalyticsReport) {
            this.UserSecurityToken = UserSecurityToken;
            this.AnalyticsReport = AnalyticsReport;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InitiateAnalyticsReportJobResponse", WrapperNamespace="http://api.eyeblaster.com/message", IsWrapped=true)]
    public partial class InitiateAnalyticsReportJobResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.eyeblaster.com/message", Order=0)]
        public SizmekApiNet.App.AnalyticsDataService.ReportBase AnalyticsReport;
        
        public InitiateAnalyticsReportJobResponse() {
        }
        
        public InitiateAnalyticsReportJobResponse(SizmekApiNet.App.AnalyticsDataService.ReportBase AnalyticsReport) {
            this.AnalyticsReport = AnalyticsReport;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAnalyticsReportJobStatusRequest", WrapperNamespace="http://api.eyeblaster.com/message", IsWrapped=true)]
    public partial class GetAnalyticsReportJobStatusRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.eyeblaster.com/message")]
        public string UserSecurityToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.eyeblaster.com/message", Order=0)]
        public SizmekApiNet.App.AnalyticsDataService.ReportBase AnalyticsReport;
        
        public GetAnalyticsReportJobStatusRequest() {
        }
        
        public GetAnalyticsReportJobStatusRequest(string UserSecurityToken, SizmekApiNet.App.AnalyticsDataService.ReportBase AnalyticsReport) {
            this.UserSecurityToken = UserSecurityToken;
            this.AnalyticsReport = AnalyticsReport;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAnalyticsReportJobStatusResponse", WrapperNamespace="http://api.eyeblaster.com/message", IsWrapped=true)]
    public partial class GetAnalyticsReportJobStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.eyeblaster.com/message", Order=0)]
        public SizmekApiNet.App.AnalyticsDataService.JobStatus Status;
        
        public GetAnalyticsReportJobStatusResponse() {
        }
        
        public GetAnalyticsReportJobStatusResponse(SizmekApiNet.App.AnalyticsDataService.JobStatus Status) {
            this.Status = Status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAnalyticsReportAsURLRequest", WrapperNamespace="http://api.eyeblaster.com/message", IsWrapped=true)]
    public partial class GetAnalyticsReportAsURLRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.eyeblaster.com/message")]
        public string UserSecurityToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.eyeblaster.com/message", Order=0)]
        public SizmekApiNet.App.AnalyticsDataService.ReportBase AnalyticsReport;
        
        public GetAnalyticsReportAsURLRequest() {
        }
        
        public GetAnalyticsReportAsURLRequest(string UserSecurityToken, SizmekApiNet.App.AnalyticsDataService.ReportBase AnalyticsReport) {
            this.UserSecurityToken = UserSecurityToken;
            this.AnalyticsReport = AnalyticsReport;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAnalyticsReportAsURLResponse", WrapperNamespace="http://api.eyeblaster.com/message", IsWrapped=true)]
    public partial class GetAnalyticsReportAsURLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.eyeblaster.com/message", Order=0)]
        public string URL;
        
        public GetAnalyticsReportAsURLResponse() {
        }
        
        public GetAnalyticsReportAsURLResponse(string URL) {
            this.URL = URL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteAnalyticsReportRequest", WrapperNamespace="http://api.eyeblaster.com/message", IsWrapped=true)]
    public partial class DeleteAnalyticsReportRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.eyeblaster.com/message")]
        public string UserSecurityToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.eyeblaster.com/message", Order=0)]
        public SizmekApiNet.App.AnalyticsDataService.ReportBase AnalyticsReport;
        
        public DeleteAnalyticsReportRequest() {
        }
        
        public DeleteAnalyticsReportRequest(string UserSecurityToken, SizmekApiNet.App.AnalyticsDataService.ReportBase AnalyticsReport) {
            this.UserSecurityToken = UserSecurityToken;
            this.AnalyticsReport = AnalyticsReport;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteReportResponse {
        
        public DeleteReportResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReportsLastAggregationTimeRequest", WrapperNamespace="http://api.eyeblaster.com/message", IsWrapped=true)]
    public partial class GetReportsLastAggregationTimeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.eyeblaster.com/message")]
        public string UserSecurityToken;
        
        public GetReportsLastAggregationTimeRequest() {
        }
        
        public GetReportsLastAggregationTimeRequest(string UserSecurityToken) {
            this.UserSecurityToken = UserSecurityToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReportsLastAggregationTimeResponse", WrapperNamespace="http://api.eyeblaster.com/message", IsWrapped=true)]
    public partial class GetReportsLastAggregationTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.eyeblaster.com/message", Order=0)]
        public SizmekApiNet.App.AnalyticsDataService.APIDateTime DateTime;
        
        public GetReportsLastAggregationTimeResponse() {
        }
        
        public GetReportsLastAggregationTimeResponse(SizmekApiNet.App.AnalyticsDataService.APIDateTime DateTime) {
            this.DateTime = DateTime;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAnalyticsDataServiceChannel : SizmekApiNet.App.AnalyticsDataService.IAnalyticsDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AnalyticsDataServiceClient : System.ServiceModel.ClientBase<SizmekApiNet.App.AnalyticsDataService.IAnalyticsDataService>, SizmekApiNet.App.AnalyticsDataService.IAnalyticsDataService {
        
        public AnalyticsDataServiceClient() {
        }
        
        public AnalyticsDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AnalyticsDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnalyticsDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnalyticsDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SizmekApiNet.App.AnalyticsDataService.InitiateAnalyticsReportJobResponse SizmekApiNet.App.AnalyticsDataService.IAnalyticsDataService.InitiateReportJob(SizmekApiNet.App.AnalyticsDataService.InitiateAnalyticsReportJobRequest request) {
            return base.Channel.InitiateReportJob(request);
        }
        
        public void InitiateReportJob(string UserSecurityToken, ref SizmekApiNet.App.AnalyticsDataService.ReportBase AnalyticsReport) {
            SizmekApiNet.App.AnalyticsDataService.InitiateAnalyticsReportJobRequest inValue = new SizmekApiNet.App.AnalyticsDataService.InitiateAnalyticsReportJobRequest();
            inValue.UserSecurityToken = UserSecurityToken;
            inValue.AnalyticsReport = AnalyticsReport;
            SizmekApiNet.App.AnalyticsDataService.InitiateAnalyticsReportJobResponse retVal = ((SizmekApiNet.App.AnalyticsDataService.IAnalyticsDataService)(this)).InitiateReportJob(inValue);
            AnalyticsReport = retVal.AnalyticsReport;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SizmekApiNet.App.AnalyticsDataService.GetAnalyticsReportJobStatusResponse SizmekApiNet.App.AnalyticsDataService.IAnalyticsDataService.GetReportJobStatus(SizmekApiNet.App.AnalyticsDataService.GetAnalyticsReportJobStatusRequest request) {
            return base.Channel.GetReportJobStatus(request);
        }
        
        public SizmekApiNet.App.AnalyticsDataService.JobStatus GetReportJobStatus(string UserSecurityToken, SizmekApiNet.App.AnalyticsDataService.ReportBase AnalyticsReport) {
            SizmekApiNet.App.AnalyticsDataService.GetAnalyticsReportJobStatusRequest inValue = new SizmekApiNet.App.AnalyticsDataService.GetAnalyticsReportJobStatusRequest();
            inValue.UserSecurityToken = UserSecurityToken;
            inValue.AnalyticsReport = AnalyticsReport;
            SizmekApiNet.App.AnalyticsDataService.GetAnalyticsReportJobStatusResponse retVal = ((SizmekApiNet.App.AnalyticsDataService.IAnalyticsDataService)(this)).GetReportJobStatus(inValue);
            return retVal.Status;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SizmekApiNet.App.AnalyticsDataService.GetAnalyticsReportAsURLResponse SizmekApiNet.App.AnalyticsDataService.IAnalyticsDataService.GetReportAsURL(SizmekApiNet.App.AnalyticsDataService.GetAnalyticsReportAsURLRequest request) {
            return base.Channel.GetReportAsURL(request);
        }
        
        public string GetReportAsURL(string UserSecurityToken, SizmekApiNet.App.AnalyticsDataService.ReportBase AnalyticsReport) {
            SizmekApiNet.App.AnalyticsDataService.GetAnalyticsReportAsURLRequest inValue = new SizmekApiNet.App.AnalyticsDataService.GetAnalyticsReportAsURLRequest();
            inValue.UserSecurityToken = UserSecurityToken;
            inValue.AnalyticsReport = AnalyticsReport;
            SizmekApiNet.App.AnalyticsDataService.GetAnalyticsReportAsURLResponse retVal = ((SizmekApiNet.App.AnalyticsDataService.IAnalyticsDataService)(this)).GetReportAsURL(inValue);
            return retVal.URL;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SizmekApiNet.App.AnalyticsDataService.DeleteReportResponse SizmekApiNet.App.AnalyticsDataService.IAnalyticsDataService.DeleteReport(SizmekApiNet.App.AnalyticsDataService.DeleteAnalyticsReportRequest request) {
            return base.Channel.DeleteReport(request);
        }
        
        public void DeleteReport(string UserSecurityToken, SizmekApiNet.App.AnalyticsDataService.ReportBase AnalyticsReport) {
            SizmekApiNet.App.AnalyticsDataService.DeleteAnalyticsReportRequest inValue = new SizmekApiNet.App.AnalyticsDataService.DeleteAnalyticsReportRequest();
            inValue.UserSecurityToken = UserSecurityToken;
            inValue.AnalyticsReport = AnalyticsReport;
            SizmekApiNet.App.AnalyticsDataService.DeleteReportResponse retVal = ((SizmekApiNet.App.AnalyticsDataService.IAnalyticsDataService)(this)).DeleteReport(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SizmekApiNet.App.AnalyticsDataService.GetReportsLastAggregationTimeResponse SizmekApiNet.App.AnalyticsDataService.IAnalyticsDataService.GetReportsLastAggregationTime(SizmekApiNet.App.AnalyticsDataService.GetReportsLastAggregationTimeRequest request) {
            return base.Channel.GetReportsLastAggregationTime(request);
        }
        
        public SizmekApiNet.App.AnalyticsDataService.APIDateTime GetReportsLastAggregationTime(string UserSecurityToken) {
            SizmekApiNet.App.AnalyticsDataService.GetReportsLastAggregationTimeRequest inValue = new SizmekApiNet.App.AnalyticsDataService.GetReportsLastAggregationTimeRequest();
            inValue.UserSecurityToken = UserSecurityToken;
            SizmekApiNet.App.AnalyticsDataService.GetReportsLastAggregationTimeResponse retVal = ((SizmekApiNet.App.AnalyticsDataService.IAnalyticsDataService)(this)).GetReportsLastAggregationTime(inValue);
            return retVal.DateTime;
        }
    }
}
